wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717061022
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.9
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
asym_block:
  desc: null
  value: 1
asym_depth:
  desc: null
  value: 1
block_depth:
  desc: null
  value: 3
bottleneck_dim:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.3
l1_lambda:
  desc: null
  value: 2.60644e-10
l1_lambda_bottleneck:
  desc: null
  value: 3.4000000000000003e-09
lambda_kl:
  desc: null
  value: 8.375e-05
lambda_mse:
  desc: null
  value: 10
lambda_perceptual:
  desc: null
  value: 4.0e-06
lambda_psnr:
  desc: null
  value: 3.0774315089e-09
lambda_ssim:
  desc: null
  value: 6.0e-06
lambda_tv:
  desc: null
  value: 1.1107568e-12
learning_rate:
  desc: null
  value: 0.000237
num_blocks:
  desc: null
  value: 4
