wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 3
bottleneck_dim:
  value: 256
dropout:
  value: 0.3
l1_lambda:
  value: 7.96460452e-07
l1_lambda_bottleneck:
  value: 4.62744e-05
lambda_kl:
  value: 4.91e-08
lambda_mse:
  value: 40
lambda_perceptual:
  value: 1.2e-05
lambda_psnr:
  value: 2.5759110419999997e-10
lambda_ssim:
  value: 0.005292
lambda_tv:
  value: 1.48240766e-11
learning_rate:
  value: 1.0e-06
num_blocks:
  value: 3
