wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 128
dropout:
  value: 0.3
l1_lambda:
  value: 3.3736679e-08
l1_lambda_bottleneck:
  value: 2.0e-10
lambda_kl:
  value: 8.749490000000001e-05
lambda_mse:
  value: 30
lambda_perceptual:
  value: 0.023959
lambda_psnr:
  value: 6.144720153e-10
lambda_ssim:
  value: 2.0e-06
lambda_tv:
  value: 7.2458474e-12
learning_rate:
  value: 1.5e-05
num_blocks:
  value: 3
