wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 3
bottleneck_dim:
  value: 128
dropout:
  value: 0.2
l1_lambda:
  value: 4.1700000000000004e-13
l1_lambda_bottleneck:
  value: 4.64e-08
lambda_kl:
  value: 8.7611e-06
lambda_mse:
  value: 90
lambda_perceptual:
  value: 3.6e-05
lambda_psnr:
  value: 2.0e-19
lambda_ssim:
  value: 0.019675
lambda_tv:
  value: 4.1e-18
learning_rate:
  value: 1.0e-05
num_blocks:
  value: 2
