wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 256
dropout:
  value: 0.2
l1_lambda:
  value: 1.42249063e-07
l1_lambda_bottleneck:
  value: 8.8094e-06
lambda_kl:
  value: 4.0e-10
lambda_mse:
  value: 70
lambda_perceptual:
  value: 1.0e-06
lambda_psnr:
  value: 1.052589405e-10
lambda_ssim:
  value: 0.010277
lambda_tv:
  value: 1.6881419899999998e-10
learning_rate:
  value: 6.0e-06
num_blocks:
  value: 3
