wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 256
dropout:
  value: 0.2
l1_lambda:
  value: 9.8232e-11
l1_lambda_bottleneck:
  value: 7.4654e-06
lambda_kl:
  value: 1.7200000000000002e-08
lambda_mse:
  value: 30
lambda_perceptual:
  value: 4.0e-06
lambda_psnr:
  value: 2.591e-16
lambda_ssim:
  value: 2.9999999999999997e-05
lambda_tv:
  value: 2.1e-18
learning_rate:
  value: 0.000542
num_blocks:
  value: 3
