wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716965675
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.9
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
block_depth:
  desc: null
  value: 1
bottleneck_dim:
  desc: null
  value: 64
l1_lambda:
  desc: null
  value: 1.0e-12
l1_lambda_bottleneck:
  desc: null
  value: 1.0e-06
lambda_kl:
  desc: null
  value: 1.0e-08
lambda_mse:
  desc: null
  value: 10
lambda_perceptual:
  desc: null
  value: 1.0e-05
lambda_psnr:
  desc: null
  value: 1.0e-07
lambda_ssim:
  desc: null
  value: 1.0e-07
lambda_tv:
  desc: null
  value: 1.0e-12
learning_rate:
  desc: null
  value: 0.0012381662813338635
num_blocks:
  desc: null
  value: 3
