wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717084056
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.11.9
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
asym_block:
  desc: null
  value: 1
asym_depth:
  desc: null
  value: 1
block_depth:
  desc: null
  value: 3
bottleneck_dim:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0
l1_lambda:
  desc: null
  value: 5.0285e-11
l1_lambda_bottleneck:
  desc: null
  value: 0
lambda_kl:
  desc: null
  value: 2.1102e-06
lambda_mse:
  desc: null
  value: 20
lambda_perceptual:
  desc: null
  value: 0.43879
lambda_psnr:
  desc: null
  value: 7.308e-18
lambda_ssim:
  desc: null
  value: 4.0e-06
lambda_tv:
  desc: null
  value: 4.534299999999999e-20
learning_rate:
  desc: null
  value: 1.198e-05
num_blocks:
  desc: null
  value: 2
