wandb_version: 1

asym_block:
  value: 0
asym_depth:
  value: 0
block_depth:
  value: 3
bottleneck_dim:
  value: 64
l1_lambda:
  value: 1.0e-09
l1_lambda_bottleneck:
  value: 0.0001
lambda_kl:
  value: 1.0e-06
lambda_mse:
  value: 10
lambda_perceptual:
  value: 1.0e-05
lambda_psnr:
  value: 1.0e-09
lambda_ssim:
  value: 1.0e-07
lambda_tv:
  value: 1.0e-09
learning_rate:
  value: 0.0051717721809941
num_blocks:
  value: 3
