wandb_version: 1

asym_block:
  value: 0
asym_depth:
  value: 0
block_depth:
  value: 2
bottleneck_dim:
  value: 64
l1_lambda:
  value: 1.0e-06
l1_lambda_bottleneck:
  value: 1.0e-06
lambda_kl:
  value: 1.0e-06
lambda_mse:
  value: 100
lambda_perceptual:
  value: 1.0e-05
lambda_psnr:
  value: 1.0e-09
lambda_ssim:
  value: 1.0e-07
lambda_tv:
  value: 1.0e-09
learning_rate:
  value: 0.0014901446087852942
num_blocks:
  value: 3
