wandb_version: 1

asym_block:
  value: 0
asym_depth:
  value: 0
block_depth:
  value: 3
bottleneck_dim:
  value: 64
l1_lambda:
  value: 1.0e-06
l1_lambda_bottleneck:
  value: 0.0001
lambda_kl:
  value: 0.0001
lambda_mse:
  value: 10
lambda_perceptual:
  value: 0.01
lambda_psnr:
  value: 1.0e-11
lambda_ssim:
  value: 1.0e-05
lambda_tv:
  value: 1.0e-09
learning_rate:
  value: 0.00970143394484894
num_blocks:
  value: 3
