wandb_version: 1

block_depth:
  value: 1
bottleneck_dim:
  value: 128
l1_lambda:
  value: 1.0e-12
l1_lambda_bottleneck:
  value: 0.0001
lambda_kl:
  value: 0.0001
lambda_mse:
  value: 100
lambda_perceptual:
  value: 1.0e-05
lambda_psnr:
  value: 1.0e-07
lambda_ssim:
  value: 1.0e-05
lambda_tv:
  value: 1.0e-12
learning_rate:
  value: 0.0016529068365879773
num_blocks:
  value: 4
