wandb_version: 1

block_depth:
  value: 1
bottleneck_dim:
  value: 256
l1_lambda:
  value: 1.0e-09
l1_lambda_bottleneck:
  value: 1.0e-08
lambda_kl:
  value: 0.0001
lambda_mse:
  value: 1
lambda_perceptual:
  value: 1.0e-05
lambda_psnr:
  value: 1.0e-11
lambda_ssim:
  value: 1.0e-06
lambda_tv:
  value: 1.0e-06
learning_rate:
  value: 0.0012912000714076597
num_blocks:
  value: 3
