wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 3
bottleneck_dim:
  value: 128
dropout:
  value: 0.4
l1_lambda:
  value: 1.5000000000000002e-14
l1_lambda_bottleneck:
  value: 5.98e-08
lambda_kl:
  value: 2.0e-10
lambda_mse:
  value: 430
lambda_perceptual:
  value: 0.006695
lambda_psnr:
  value: 7.284938976e-10
lambda_ssim:
  value: 0.056406
lambda_tv:
  value: 2.525110845e-10
learning_rate:
  value: 4.8e-05
num_blocks:
  value: 2
