wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 256
dropout:
  value: 0.2
l1_lambda:
  value: 9.7e-14
l1_lambda_bottleneck:
  value: 1.5e-09
lambda_kl:
  value: 6.0e-10
lambda_mse:
  value: 30
lambda_perceptual:
  value: 2.0e-06
lambda_psnr:
  value: 1.752792811e-10
lambda_ssim:
  value: 0.006973
lambda_tv:
  value: 7.561e-16
learning_rate:
  value: 2.9e-05
num_blocks:
  value: 2
