wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 3
bottleneck_dim:
  value: 128
dropout:
  value: 0.2
l1_lambda:
  value: 6.5495336e-08
l1_lambda_bottleneck:
  value: 2.0e-09
lambda_kl:
  value: 1.1e-09
lambda_mse:
  value: 60
lambda_perceptual:
  value: 0.001864
lambda_psnr:
  value: 6.5e-18
lambda_ssim:
  value: 2.1e-05
lambda_tv:
  value: 2.0e-19
learning_rate:
  value: 0.000265
num_blocks:
  value: 3
