wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 3
bottleneck_dim:
  value: 128
dropout:
  value: 0.4
l1_lambda:
  value: 3.0000000000000002e-15
l1_lambda_bottleneck:
  value: 1.4900000000000001e-08
lambda_kl:
  value: 4.0e-10
lambda_mse:
  value: 20
lambda_perceptual:
  value: 0.000164
lambda_psnr:
  value: 2.35580365e-11
lambda_ssim:
  value: 0.002668
lambda_tv:
  value: 6.649330999999999e-13
learning_rate:
  value: 0.000361
num_blocks:
  value: 3
