wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 256
dropout:
  value: 0.4
l1_lambda:
  value: 3.1e-14
l1_lambda_bottleneck:
  value: 1.5e-09
lambda_kl:
  value: 9.15e-08
lambda_mse:
  value: 20
lambda_perceptual:
  value: 2.0e-06
lambda_psnr:
  value: 4.0e-19
lambda_ssim:
  value: 0.001961
lambda_tv:
  value: 2.2077e-15
learning_rate:
  value: 4.1e-05
num_blocks:
  value: 3
