wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 256
dropout:
  value: 0.2
l1_lambda:
  value: 5.19e-13
l1_lambda_bottleneck:
  value: 3.787e-06
lambda_kl:
  value: 8.5084e-06
lambda_mse:
  value: 120
lambda_perceptual:
  value: 0.075266
lambda_psnr:
  value: 6.20542e-14
lambda_ssim:
  value: 0.0016079999999999998
lambda_tv:
  value: 1.1962e-15
learning_rate:
  value: 1.3e-05
num_blocks:
  value: 4
