wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 64
dropout:
  value: 0.3
l1_lambda:
  value: 1.0890000000000001e-12
l1_lambda_bottleneck:
  value: 1.896e-07
lambda_kl:
  value: 1.0e-10
lambda_mse:
  value: 70
lambda_perceptual:
  value: 0.000334
lambda_psnr:
  value: 3.0e-19
lambda_ssim:
  value: 2.5e-05
lambda_tv:
  value: 2.959180419e-10
learning_rate:
  value: 0.000121
num_blocks:
  value: 2
