wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717046976
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.11.9
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
asym_block:
  desc: null
  value: 1
asym_depth:
  desc: null
  value: 1
block_depth:
  desc: null
  value: 2
bottleneck_dim:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.2
l1_lambda:
  desc: null
  value: 2.8010000000000007e-12
l1_lambda_bottleneck:
  desc: null
  value: 1.9e-09
lambda_kl:
  desc: null
  value: 4.278e-07
lambda_mse:
  desc: null
  value: 10
lambda_perceptual:
  desc: null
  value: 0.051848
lambda_psnr:
  desc: null
  value: 1.5909999999999999e-16
lambda_ssim:
  desc: null
  value: 0.021551
lambda_tv:
  desc: null
  value: 3.8181e-15
learning_rate:
  desc: null
  value: 0.000606
num_blocks:
  desc: null
  value: 2
