wandb_version: 1

block_depth:
  value: 2
bottleneck_dim:
  value: 256
l1_lambda:
  value: 1.0e-06
l1_lambda_bottleneck:
  value: 1.0e-08
lambda_kl:
  value: 1.0e-06
lambda_mse:
  value: 1
lambda_perceptual:
  value: 0.01
lambda_psnr:
  value: 1.0e-09
lambda_ssim:
  value: 1.0e-06
lambda_tv:
  value: 1.0e-06
learning_rate:
  value: 0.00404724191382058
num_blocks:
  value: 3
