wandb_version: 1

block_depth:
  value: 1
bottleneck_dim:
  value: 64
l1_lambda:
  value: 1.0e-06
l1_lambda_bottleneck:
  value: 0.0001
lambda_kl:
  value: 0.0001
lambda_mse:
  value: 100
lambda_perceptual:
  value: 0.01
lambda_psnr:
  value: 1.0e-09
lambda_ssim:
  value: 1.0e-07
lambda_tv:
  value: 1.0e-09
learning_rate:
  value: 0.009523738813002064
num_blocks:
  value: 2
