wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 3
bottleneck_dim:
  value: 128
l1_lambda:
  value: 1.0e-06
l1_lambda_bottleneck:
  value: 0.0001
lambda_kl:
  value: 1.0e-06
lambda_mse:
  value: 100
lambda_perceptual:
  value: 0.001
lambda_psnr:
  value: 1.0e-07
lambda_ssim:
  value: 1.0e-05
lambda_tv:
  value: 1.0e-06
learning_rate:
  value: 0.007837481802141532
num_blocks:
  value: 3
