wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 128
l1_lambda:
  value: 1.0e-12
l1_lambda_bottleneck:
  value: 1.0e-06
lambda_kl:
  value: 0.0001
lambda_mse:
  value: 10
lambda_perceptual:
  value: 0.01
lambda_psnr:
  value: 1.0e-09
lambda_ssim:
  value: 1.0e-06
lambda_tv:
  value: 1.0e-12
learning_rate:
  value: 0.005603915468004072
num_blocks:
  value: 2
