wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716966065
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.9
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
asym_block:
  desc: null
  value: 0
asym_depth:
  desc: null
  value: 0
block_depth:
  desc: null
  value: 3
bottleneck_dim:
  desc: null
  value: 64
l1_lambda:
  desc: null
  value: 1.0e-06
l1_lambda_bottleneck:
  desc: null
  value: 0.0001
lambda_kl:
  desc: null
  value: 0.0001
lambda_mse:
  desc: null
  value: 10
lambda_perceptual:
  desc: null
  value: 0.01
lambda_psnr:
  desc: null
  value: 1.0e-11
lambda_ssim:
  desc: null
  value: 1.0e-05
lambda_tv:
  desc: null
  value: 1.0e-09
learning_rate:
  desc: null
  value: 0.00970143394484894
num_blocks:
  desc: null
  value: 3
