wandb_version: 1

asym_block:
  value: 1
asym_depth:
  value: 1
block_depth:
  value: 2
bottleneck_dim:
  value: 64
dropout:
  value: 0.4
l1_lambda:
  value: 1.2e-14
l1_lambda_bottleneck:
  value: 1.6271600000000002e-05
lambda_kl:
  value: 1.8e-09
lambda_mse:
  value: 10
lambda_perceptual:
  value: 6.0e-06
lambda_psnr:
  value: 4.1e-17
lambda_ssim:
  value: 2.3e-05
lambda_tv:
  value: 6.46e-17
learning_rate:
  value: 0.009827
num_blocks:
  value: 4
