wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717051872
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.9
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
asym_block:
  desc: null
  value: 1
asym_depth:
  desc: null
  value: 1
block_depth:
  desc: null
  value: 2
bottleneck_dim:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.2
l1_lambda:
  desc: null
  value: 9.885825800000001e-08
l1_lambda_bottleneck:
  desc: null
  value: 2.5700000000000002e-08
lambda_kl:
  desc: null
  value: 3.84168e-05
lambda_mse:
  desc: null
  value: 50
lambda_perceptual:
  desc: null
  value: 0.049682
lambda_psnr:
  desc: null
  value: 3.022e-16
lambda_ssim:
  desc: null
  value: 0.009165
lambda_tv:
  desc: null
  value: 1.6745e-15
learning_rate:
  desc: null
  value: 0.000389
num_blocks:
  desc: null
  value: 3
